name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # or your desired version



  deploy:
    name: Deploy Streamlit App
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push changes to Hugging Face Space
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}  
        run: |
          cd Suerz/MLOps2
          git config --global user.email "shubhamsaklani94@gmail.com"
          git config --global user.name "Suerz"
          git add .
          git commit -m "Deploy Streamlit app and model"
          git push
