name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Model
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run the model training script to generate the .pkl file
      - name: Train model and save as .pkl
        run: |
          python best_model.py

      # Step 5: Upload the trained model as an artifact for reuse
      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: best_model.pkl

  deploy:
    name: Deploy Streamlit App
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Download the model artifact from the previous job
      - name: Download model artifact
        uses: actions/download-artifact@v3
        with:
          name: trained-model

      # Step 5: Run the Streamlit app
      - name: Run Streamlit app
        run: |
          streamlit run app.py
