name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Model
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      

  deploy:
    name: Deploy Streamlit App
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'


       # Step 4: Download the model artifact from Hugging Face
      - name: Download model from Hugging Face
        run: |
          pip install huggingface_hub
          python -c "
          from huggingface_hub import hf_hub_download
          hf_hub_download(repo_id='Suerz/MLOpsAssignment', filename='best_model.pkl', local_dir='.')
          "
      - name: Copy model to repo
        run: |
          cp best_model.pkl ./

      - name: Commit changes
        run: |
          git config --global user.name "shubhamsaklani94@gmail.com"
          git config --global user.email "shubhamsaklani"
          git add ./best_model.pkl
          git commit -m "Add best_model.pkl from Hugging Face"

      - name: Push to repository
        run: |
          git push origin main
      
      # Step 5: Push changes to Hugging Face Space
      - name: Configure Git
        run: |
          git config --global user.email "shubhamsaklani94@gmail.com"
          git config --global user.name "shubhamsaklani"

      - name: Push changes to Hugging Face Space
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}  
        run: |
          git pull --rebase https://Suerz:$HUGGINGFACE_TOKEN@huggingface.co/spaces/Suerz/MLOps2 main || true
          git push https://Suerz:$HUGGINGFACE_TOKEN@huggingface.co/spaces/Suerz/MLOps2 main