name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Model
    runs-on: ubuntu-latest

    steps:
      

       # Step 5: Upload the trained model to Hugging Face
      - name: Upload model to Hugging Face
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}  
        run: |
          pip install huggingface_hub
          python -c "
          from huggingface_hub import login, upload_file
          login(token='${{ secrets.HUGGINGFACE_TOKEN }}')
          upload_file(
              path_or_fileobj='best_model.pkl',
              path_in_repo='best_model.pkl',
              repo_id='Suerz/MLOpsAssignment',
              repo_type='model'
          )
          " 

  deploy:
    name: Deploy Streamlit App
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 5: Push changes to Hugging Face Space
      - name: Push changes to Hugging Face Space
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}  
        run: |
          cd MLOps2
          git config --global user.email "shubhamsaklani94@gmail.com"
          git config --global user.name "Suerz"
          git add .
          git commit -m "Deploy Streamlit app and model"
          git push
